### PR TITLE
Don't allow search form submit with empty value fix #8

### LINKED ISSUE #8: Don't allow search form submit with empty value
Form should do any action

### PR DESCRIPTION
**Pull request by brunomachado**

### CODE REVIEW

**Comment by filipewl** [comment]
It looks okay by me. Did you ask @sergiofontes if we need to show any error message? In my opinion it should stay as it is now: when the input is blank, the form shouldn't be submited, no errors needed. It's the same with google.com.

**Comment by jessicabarbalho** [comment]
@filipewl We asked him and he said the form has to do nothing. Like you suggested.

**Comment by jessicabarbalho** [comment]
@brunomachado when you finish the corrections let me know :+1:

**Comment by brunomachado** [comment]
@jessicabarbalho, done.

**Comment by jessicabarbalho** [comment]
@brunomachado you can remove the branch :smiley:

**Pull request merged**
